#!/usr/bin/env python



import fileinput

from rxn.chemutils.miscellaneous import canonicalize_any


def canonicalize() -> None:
    """
    Canonicalize SMILES strings (molecules or reactions).

    The script will read strings either from stdin, or from a file given as the
    first argument (behavior from the fileinput package)."""

    for line in fileinput.input():
        smiles = line.strip()
        print(canonicalize_any(smiles))


if __name__ == '__main__':
    canonicalize()
