#!/usr/bin/env python

# LICENSED INTERNAL CODE. PROPERTY OF IBM.
# IBM Research Zurich Licensed Internal Code
# (C) Copyright IBM Corp. 2021
# ALL RIGHTS RESERVED

import fileinput

from rxn_chemutils.extended_reaction_smiles import to_extended_reaction_smiles
from rxn_chemutils.reaction_equation import ReactionEquation
from rxn_chemutils.tokenization import detokenize_smiles


def depictready() -> None:
    """
    Makes SMILES strings (molecules or reactions) ready for depiction.

    I.e., the input will be detokenized and the fragemnt information reformulated
    into an extended SMILES notation.

    The script will read strings either from stdin, or from a file given as the
    first argument (behavior from the fileinput package)."""

    for line in fileinput.input():
        smiles = line.strip()
        detokenized_smiles = detokenize_smiles(smiles)
        try:
            reaction_equation = ReactionEquation.from_string(
                detokenized_smiles, '~')
            extended_smiles = to_extended_reaction_smiles(reaction_equation)
            print(extended_smiles)
        except Exception:
            print(detokenized_smiles.replace('~', '.'))


if __name__ == '__main__':
    depictready()
